---
- name: Provision FlokiNET redirector instance
  hosts: redirectors
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - include: redirector.yml
      
- name: Provision FlokiNET C2 instance
  hosts: c2servers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    redirector_ip: "{{ hostvars[groups['redirectors'][0]]['ansible_host'] }}"
  tasks:
    - include: c2.yml